# Generated by Django 4.0.1 on 2022-04-08 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_processpayments_is_paid_within_the_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientappointment',
            name='donePayment',
            field=models.BooleanField(default=False),
        ),
    ]
